# Generated by Django 4.2 on 2025-08-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockreport', '0003_rename_stockreport__user_id_8f9c8c_idx_stockreport_user_id_4cdd56_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemParamDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('VchType', models.CharField(max_length=10)),
                ('VchNo', models.CharField(max_length=10)),
                ('C1', models.CharField(blank=True, max_length=50)),
                ('C2', models.CharField(blank=True, max_length=50)),
                ('C3', models.CharField(blank=True, max_length=50)),
                ('C4', models.CharField(blank=True, max_length=50)),
                ('C5', models.CharField(blank=True, max_length=50)),
                ('D3', models.FloatField(blank=True, verbose_name='Mrp')),
                ('D4', models.FloatField(blank=True, verbose_name='sale price')),
                ('BCN', models.CharField(blank=True, max_length=50)),
                ('Value1', models.FloatField(default=0, verbose_name='quantity')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockreport.master1')),
            ],
        ),
    ]
