# Generated by Django 5.2.5 on 2025-08-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockreport', '0004_itemparamdet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemparamdet',
            name='BCN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='C1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='C2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='C3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='C4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='C5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='VchNo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itemparamdet',
            name='VchType',
            field=models.CharField(max_length=20),
        ),
    ]
